const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),path=require('node:path');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const now=Date.parse('2026-09-10T12:00:00Z');
function setup(){const c={window:{},crypto:crypto.webcrypto,structuredClone};vm.createContext(c);for(const file of ['shop-catalog.js','token-rewards-config.js','token-rewards-rules.js','lounge-games.js','lounge-extra-rules.js','game-cards.js'])vm.runInContext(read(file),c);let source=read('player-engine.js').replace(/^import .+;$/gm,'').replace(/^export .+;$/gm,'');vm.runInContext(source+'\nglobalThis.engine={apply,fresh,view};',c);return {e:c.engine,cards:c.window.GAME_CARDS};}
test('Usernames and starting wallets retain the expected rules',()=>{const {e}=setup();assert.throws(()=>e.fresh('admin',now));assert.throws(()=>e.fresh('bad name',now));const w=e.fresh('Player_One',now);assert.equal(w.balance,1000);assert.equal(w.usernameKey,'player_one');});
test('Permanent purchases deduct once and require ownership to equip',()=>{const {e}=setup(),w=e.fresh('PlayerOne',now);e.apply(w,'buy',{id:'badge-star'},now);assert.equal(w.balance,750);assert.throws(()=>e.apply(w,'buy',{id:'badge-star'},now),/already own/);assert.throws(()=>e.apply(w,'equip',{category:'badge',id:'badge-crown'},now),/Buy/);e.apply(w,'equip',{category:'badge',id:'badge-star'},now);assert.equal(w.equipped.badge,'badge-star');e.apply(w,'equip',{category:'badge',id:null},now);assert.equal(w.equipped.badge,undefined);assert.equal(w.balance,750);});
test('Daily challenge progress follows the shared five-minute card reward',()=>{const {e,cards}=setup(),w=e.fresh('PlayerOne',now);const click=(i,t)=>e.apply(w,'reward',{kind:'card',payload:{code:cards[i].code}},t);click(0,now);click(1,now+1000);assert.equal(w.rewards.daily.games.length,1);assert.equal(w.balance,1050);click(1,now+300000);click(2,now+600000);assert.equal(w.rewards.daily.games.length,3);assert.equal(w.balance,1150);e.apply(w,'reward',{kind:'daily',payload:{id:'daily-explorer',day:'2026-09-10'}},now+600000);assert.equal(w.balance,1250);});
test('Whole-token all-in bets work; overdrafts and repeated settlement fail',()=>{const {e}=setup(),w=e.fresh('PlayerOne',now);assert.throws(()=>e.apply(w,'instant',{game:'coin',stake:1001},now,()=>0));e.apply(w,'start',{game:'roulette',stake:1000,choice:'red'},now,()=>1);const r=w.games.roulette;assert.throws(()=>e.apply(w,'move',{game:'roulette',id:r.id,revision:0,move:'skip'},now+10),/need 5/);e.apply(w,'move',{game:'roulette',id:r.id,revision:0,move:'finish'},now+7000);assert.equal(w.balance,2000);assert.throws(()=>e.apply(w,'move',{game:'roulette',id:r.id,revision:1,move:'finish'},now+7000));});
test('The page view conceals unrevealed games without claiming server secrecy',()=>{const {e}=setup(),w=e.fresh('PlayerOne',now);e.apply(w,'start',{game:'mines',stake:10},now,()=>0);e.apply(w,'start',{game:'crash',stake:10},now,()=>500000);const view=e.view(w);assert.ok(view.games.mines.mines.every(i=>i===-1));assert.equal(view.games.crash.crashAt,undefined);assert.ok(w.games.crash.crashAt>1);});
